# MD013:
# Number of characters
# line_length: 120
# Number of characters for headings
# heading_line_length: 120
# Number of characters for code blocks
# code_block_line_length: 120
# Include code blocks
# code_blocks: true
# Include tables
# tables: true
# Include headings
# headings: true
# Strict length checking
# strict: false
# Stern length checking
# stern: false
MD033:
  # Allowed elements
  allowed_elements: [a, img]

# Disable rule for spaces inside link text
MD039: false
# Disable line length for debugging
MD013: false
