- name: Configure the server
  hosts: localhost
  tags: algo
  vars_files:
    - config.cfg

  pre_tasks:
    - block:
      - name: Local pre-tasks
        include_tasks: playbooks/local.yml
        tags: [ 'always' ]
      rescue:
        - debug: var=fail_hint
          tags: always
        - fail:
          tags: always

  roles:
    - { role: cloud-digitalocean, tags: ['digitalocean'] }
    - { role: cloud-ec2, tags: ['ec2'] }
    - { role: cloud-gce, tags: ['gce'] }
    - { role: cloud-azure, tags: ['azure'] }
    - { role: cloud-lightsail, tags: ['lightsail'] }
    - { role: cloud-scaleway, tags: ['scaleway'] }
    - { role: cloud-openstack, tags: ['openstack'] }
    - { role: local, tags: ['local'] }

  post_tasks:
    - block:
      - name: Local post-tasks
        include_tasks: playbooks/post.yml
        become: false
        tags: [ 'cloud' ]
      rescue:
        - debug: var=fail_hint
          tags: always
        - fail:
          tags: always

- name: Configure the server and install required software
  hosts: vpn-host
  gather_facts: false
  tags: algo
  become: true
  vars_files:
    - config.cfg

  pre_tasks:
    - block:
      - name: Common pre-tasks
        include_tasks: playbooks/common.yml
        tags: [ 'digitalocean', 'ec2', 'gce', 'azure', 'lightsail', 'scaleway', 'openstack', 'local', 'pre' ]
      rescue:
        - debug: var=fail_hint
          tags: always
        - fail:
          tags: always

  roles:
    - { role: dns_adblocking, tags: [ 'dns', 'adblock' ] }
    - { role: ssh_tunneling, tags: [ 'ssh_tunneling' ] }
    - { role: vpn, tags: [ 'vpn' ] }

  post_tasks:
    - block:
      - name: Delete the CA key
        local_action:
          module: file
          path: "configs/{{ IP_subject_alt_name }}/pki/private/cakey.pem"
          state: absent
        become: false
        when: not Store_CAKEY

      - name: Dump the configuration
        local_action:
          module: copy
          dest: "configs/{{ IP_subject_alt_name }}/config.yml"
          content: |
            server_ip: {{ ansible_ssh_host }}
            server_user: {{ ansible_ssh_user }}
            ansible_ssh_private_key_file: {{ ansible_ssh_private_key_file|default(SSH_keys.private) }}
            ssh_tunneling: {{ ssh_tunneling }}
            IP_subject_alt_name: {{ IP_subject_alt_name }}
            OnDemandEnabled_Cellular: {{ OnDemandEnabled_Cellular }}
            OnDemandEnabled_WIFI: {{ OnDemandEnabled_WIFI }}
            OnDemandEnabled_WIFI_EXCLUDE: '{{ OnDemandEnabled_WIFI_EXCLUDE }}'
            Win10_Enabled: {{ Win10_Enabled }}
        become: false

      - debug:
          msg:
            - "{{ congrats.common.split('\n') }}"
            - "    {{ congrats.p12_pass }}"
            - "    {% if Store_CAKEY %}{{ congrats.ca_key_pass }}{% endif %}"
            - "    {% if cloud_deployment is defined %}{{ congrats.ssh_access }}{% endif %}"
      tags: always
      rescue:
        - debug: var=fail_hint
          tags: always
        - fail:
          tags: always

    - name: Save the CA key password
      local_action: >
        shell echo "{{ easyrsa_CA_password }}" > /tmp/ca_password
      become: no
      tags: tests
