---
collections:
  - name: ansible.posix
    version: ">=2.1.0"
  - name: community.general
    version: ">=11.1.0"
  - name: community.crypto
    version: ">=3.0.3"
  - name: openstack.cloud
    version: ">=2.4.1"
