---
collections:
  - name: ansible.posix
    version: "==2.2.2"
  - name: ansible.utils
    version: "==6.1.0"
  - name: community.general
    version: "==13.3.0"
  - name: community.crypto
    version: "==3.3.0"
  - name: openstack.cloud
    version: "==2.6.0"
  - name: linode.cloud
    version: "==0.41.0"
  - name: community.digitalocean
    version: "==1.26.0"
  - name: azure.azcollection
    version: "==3.21.0"
  - name: vultr.cloud
    version: "==1.14.1"
  - name: amazon.aws
    version: "==11.4.0"
  - name: google.cloud
    version: "==1.14.0"
  - name: hetzner.hcloud
    version: "==6.10.0"
  - name: ngine_io.cloudstack
    version: "==3.0.0"
