---
collections:
  - name: ansible.posix
    version: ">=1.6.2"
  - name: community.general
    version: ">=8.6.11"
  - name: community.crypto
    version: ">=2.26.4"
  - name: openstack.cloud
    version: ">=2.4.1"
