---
- name: restart strongswan
  service: name={{ strongswan_service }} state=restarted
  tags:
    - service_management

- name: daemon-reload
  systemd: daemon_reload=true
  tags:
    - service_management

- name: restart apparmor
  service: name=apparmor state=restarted
  tags:
    - service_management
    - apparmor

- name: rereadcrls
  shell: ipsec rereadcrls; ipsec purgecrls
