---
- name: restart strongswan
  block:
    - name: restart strongswan service
      service: name={{ strongswan_service }} state=restarted

    - name: wait for strongswan to be ready
      wait_for:
        port: 500
        host: 127.0.0.1
        delay: 2
        timeout: 30
        state: started

- name: daemon-reload
  systemd: daemon_reload=true

- name: restart apparmor
  service: name=apparmor state=restarted

- name: rereadcrls
  block:
    - name: reload certificate revocation lists
      command: ipsec rereadcrls
      register: rereadcrls_result
      retries: 3
      delay: 2
      until: rereadcrls_result.rc == 0

    - name: purge old certificate revocation lists
      command: ipsec purgecrls
