---
- name: restart strongswan
  service: name={{ strongswan_service }} state=restarted
  notify: wait for strongswan

- name: wait for strongswan
  wait_for:
    port: 500
    host: 127.0.0.1
    delay: 2
    timeout: 30
    state: started

- name: daemon-reload
  systemd: daemon_reload=true

- name: restart apparmor
  service: name=apparmor state=restarted

- name: rereadcrls
  command: ipsec rereadcrls
  register: rereadcrls_result
  retries: 3
  delay: 2
  until: rereadcrls_result.rc == 0
  notify: purgecrls

- name: purgecrls
  command: ipsec purgecrls
