---
- name: Include prompts
  import_tasks: prompts.yml

- environment:
    SCW_TOKEN: "{{ algo_scaleway_token }}"
  block:
    - name: Set Scaleway API zone name
      set_fact:
        scaleway_zone: >-
          {{ scaleway_regions | selectattr('alias', 'equalto', algo_region) | map(attribute='zone') | first }}

    - name: Get Ubuntu image ID from Scaleway Marketplace API
      uri:
        url: "https://api.scaleway.com/marketplace/v2/local-images?image_label={{ cloud_providers.scaleway.image_label }}&zone={{ scaleway_zone }}"
        method: GET
        return_content: true
      register: marketplace_images

    - name: Find Ubuntu local image ID
      set_fact:
        scaleway_image_id: >-
          {{ (marketplace_images.json.local_images |
              selectattr('arch', 'equalto', cloud_providers.scaleway.arch) |
              selectattr('type', 'equalto', 'instance_local') |
              first).id }}

    - name: Create a server
      scaleway_compute:
        name: "{{ algo_server_name }}"
        enable_ipv6: true
        public_ip: dynamic
        boot_type: local
        state: present
        image: "{{ scaleway_image_id }}"
        organization: "{{ algo_scaleway_org_id }}"
        region: "{{ algo_region }}"
        commercial_type: "{{ cloud_providers.scaleway.size }}"
        wait: true
        tags:
          - Environment:Algo
          - AUTHORIZED_KEY={{ lookup('file', SSH_keys.public) | regex_replace(' ', '_') }}
      register: scaleway_compute

    - name: Patch the cloud-init
      uri:
        url: https://cp-{{ algo_region }}.scaleway.com/servers/{{ scaleway_compute.msg.id }}/user_data/cloud-init
        method: PATCH
        body: "{{ lookup('template', 'files/cloud-init/base.yml') }}"
        status_code: 204
        headers:
          Content-Type: text/plain
          X-Auth-Token: "{{ algo_scaleway_token }}"

    - name: Start the server
      scaleway_compute:
        name: "{{ algo_server_name }}"
        enable_ipv6: true
        public_ip: dynamic
        boot_type: local
        state: running
        image: "{{ scaleway_image_id }}"
        organization: "{{ algo_scaleway_org_id }}"
        region: "{{ algo_region }}"
        commercial_type: "{{ cloud_providers.scaleway.size }}"
        wait: true
        tags:
          - Environment:Algo
          - AUTHORIZED_KEY={{ lookup('file', SSH_keys.public) | regex_replace(' ', '_') }}
      register: algo_instance
      until: algo_instance.msg.public_ip is not none
      retries: 3
      delay: 3

- set_fact:
    cloud_instance_ip: "{{ algo_instance.msg.public_ip.address }}"
    ansible_ssh_user: algo
    ansible_ssh_port: "{{ ssh_port }}"
    cloudinit: true
